name: freezed_sample
description: A sample command-line application to test the Freezed package.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  freezed_annotation:
  meta: ^1.2.4
  path: ^1.7.0

dev_dependencies:
  build_runner:
  freezed:
  test: ^1.14.4
  very_good_analysis: ^1.0.4


